using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace CityOfCapeTown.Migration;

/// <summary>
/// Intercepts requests to old SharePoint URLs and 301-redirects them to
/// their Umbraco equivalents using the url_map.json generated by the scraper.
///
/// Register in Program.cs:
///   app.UseMiddleware&lt;LegacyRedirectMiddleware&gt;();
///   // Must come BEFORE app.UseUmbraco...
/// </summary>
public class LegacyRedirectMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<LegacyRedirectMiddleware> _logger;

    // Loaded once at startup
    private readonly Dictionary<string, string> _map;

    public LegacyRedirectMiddleware(
        RequestDelegate next,
        ILogger<LegacyRedirectMiddleware> logger,
        IWebHostEnvironment env)
    {
        _next   = next;
        _logger = logger;
        _map    = LoadMap(env.ContentRootPath);
        _logger.LogInformation("LegacyRedirectMiddleware loaded {Count} URL mappings", _map.Count);
    }

    public async Task InvokeAsync(HttpContext context)
    {
        var path = context.Request.Path.Value ?? "/";

        // Normalise: decode %20 etc. and strip trailing slash
        var decoded  = Uri.UnescapeDataString(path).TrimEnd('/');
        var decodedLower = decoded.ToLowerInvariant();

        // Try exact match first, then case-insensitive
        if (_map.TryGetValue(decoded, out var newPath) ||
            _map.TryGetValue(decodedLower, out newPath))
        {
            _logger.LogDebug("301 {OldPath} → {NewPath}", path, newPath);
            context.Response.StatusCode  = StatusCodes.Status301MovedPermanently;
            context.Response.Headers.Location = newPath;
            return;
        }

        await _next(context);
    }

    // -------------------------------------------------------------------------

    private static Dictionary<string, string> LoadMap(string contentRoot)
    {
        // Look for url_map.json in well-known locations
        var candidates = new[]
        {
            Path.Combine(contentRoot, "migration", "url_map.json"),
            Path.Combine(contentRoot, "App_Data", "url_map.json"),
            Path.Combine(contentRoot, "url_map.json"),
        };

        foreach (var path in candidates)
        {
            if (!File.Exists(path)) continue;

            var json = File.ReadAllText(path);
            var raw  = JsonSerializer.Deserialize<Dictionary<string, string>>(json)
                       ?? new Dictionary<string, string>();

            // Build a case-insensitive lookup with both encoded and decoded keys
            var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var (k, v) in raw)
            {
                map.TryAdd(k, v);
                map.TryAdd(Uri.UnescapeDataString(k), v);
            }
            return map;
        }

        return new Dictionary<string, string>();
    }
}
